### ISSUE TITLE
/bin/sh: /usr/lib/jamovi/lib/R/bin/R: No such file or directory

### ISSUE THREAD

**Issue by stephensrmmartin** [jamovi/jamovi-compiler#33]
When compiling the jamovi-rbundle for arch linux, the following error occurs at the point of running the jmv compiler on the jmv package:

`/bin/sh: /usr/lib/jamovi/lib/R/bin/R: No such file or directory`

I'm not sure what it's intending to do. I assume this is a consequence of building everything into jamovi itself (R included), but that's against R packaging guidelines. Either there should be a directive to the compiler [and jamovi?] stating either at compile or run time where to find R, or perhaps there could be a link made in the jamovi package itself, such that /usr/lib/jamovi/lib/R -> /usr/lib/R/ ?

**Comment by jonathon-love** [comment]
hi stephen,

sorry for the inconvenience &nbsp; it didn't occur to me how this would impact you. i've added a `--rhome` option (allowing you to specify the `R_HOME`) to the `jmc` command now.

with thanks

**Comment by jonathon-love** [comment]
(a heads-up, i've changed where the Makefile looks for R. i made this change a while ago, but hadn't committed because i figured it would break your stuff. you patch the makefile, yeah? so it's not a big deal?)

**Comment by stephensrmmartin** [comment]
I do patch it yes; ideally there would be a makefile or configure directive that allows me to say where R is, but it's not a terrible inconvenience to just patch it to use the arch location.
