### ISSUE TITLE
flatpak: "unable to determine R version"

### ISSUE THREAD

**Issue by SvenHeimbuch** [jamovi/jamovi-compiler#43]
When I try to install (or build) a module via cli into my Linux flatpak install, I always get the error message: "unable to determine R version"

I invoke this command: 
`jmc --install flexplot.jmo --home="flatpak"`

And this is what I get in the terminal: 

`jamovi compiler`
`jamovi found at /usr/bin/flatpak`
`unable to determine R version`

**Comment by jonathon-love** [comment]
righto. i'll take a look. but you don't actually install .jmo's in that way, however.

go to the jamovi library (from the modules menu at the top right), and select side-load, then select the .jmo file from there.

cheers

**Comment by SvenHeimbuch** [comment]
Yeah, I know that this is not the usual way. But I wanted to try it on a server we're running. And yet, it is not possible to sideload modules via browser. And it's also not just the install part, I get the same error when I try to build a module with jmc.

**Comment by jonathon-love** [comment]
you can just find the modules folder, and unzip the .jmo file into it -- alongside `jmv` and `base` ... then restart the server.

**Comment by jonathon-love** [comment]
or i think you can go `jamovi --install path/to/module.jmo`

**Comment by jonathon-love** [comment]
`jmc` determines the R version by running `flatpak run org.jamovi.jamovi -R --version` and parsing the output. could you try running `flatpak run org.jamovi.jamovi -R --version` and see what it outputs?

**Comment by SvenHeimbuch** [comment]
`flatpak run org.jamovi.jamovi -R --version`
`R version 3.5.1 (2018-07-02) -- "Feather Spray"`
`Copyright (C) 2018 The R Foundation for Statistical Computing`
`Platform: x86_64-pc-linux-gnu (64-bit)`

This part seems to work. But when I try to use `jmc` I always get the error message.

**Comment by jonathon-love** [comment]
ah! it *actually* runs this:

`flatpak run --devel org.jamovi.jamovi -R --version`

does the `--devel` argument causes it to throw an error?

**Comment by jonathon-love** [comment]
i think that's what's happening here ... you'll see you need to install another thing before jmc will work. the error message should tell you what.

**Comment by SvenHeimbuch** [comment]
No error when using the `--devel` switch. I get the same output as above.

Btw. the workaround for installing by just unzipping and restarting the jamovi server works perfectly fine.

**Comment by jonathon-love** [comment]
hmm, well if you want to do some more forensics, this is the code responsible:

https://github.com/jamovi/jamovi-compiler/blob/master/index.js#L154-L157

jonathon

**Comment by jonathon-love** [comment]
sorry @SvenHeimbuch,

i swear i couldn't reproduce this before, but it's clear as day today. sorry for the delay.

jonathon
