### ISSUE TITLE
Failure to link dynamic library

### ISSUE THREAD

**Issue by brandmaier** [jamovi/jamovi-compiler#53]
I would love to build my own jamovi plugin but I have trouble getting the compiler to run. I am running a macOS (Catalina) machine with R 4.1 (but I also tried the same with R 4.0). I have a working jamovi installation. If I do
```
jmc --check
```
I get this:
```
jamovi compiler

jamovi 1.6.23 found at /Applications/jamovi.app
```
However, if I try to compile my module, I get this error:
```

 jmc --build crit

jamovi compiler

jamovi 1.6.23 found at /Applications/jamovi.app
wrote: quantile.h.R
wrote: quantile.u.yaml
wrote: quantile.src.js
wrote: quantile.js
writing module meta
wrote: 0000.yaml
wrote: jamovi.yaml
wrote: jamovi-full.yaml
dyld: Library not loaded: @executable_path/../Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
  Referenced from: /Applications/jamovi.app/Contents/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
  Reason: image not found
/Applications/jamovi.app/Contents/Frameworks/R.framework/Versions/Current/Resources/bin/INSTALL: line 34: 47030 Done                    echo 'tools:::.install_packages()'
     47031 Abort trap: 6           | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}

Could not build module
```
Have you seen this before? Do you have an idea how I can fix the missing link to the dynamic library (which does exist in my local R installation). Thank you so much!

**Comment by brandmaier** [comment]
I realise now that this is related to the Apple security police issue with signed/unsigned applications. I am closing this now as it seems to be a known issue. Thanks!

**Comment by jonathon-love** [comment]
yeah, use the jamovi-unsigned.zip and you'll be in business
